/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Sep-2024 1:16:54 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cita control_Historial Cita]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cita control] DROP CONSTRAINT [FK_Cita control_Historial Cita]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cita control]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cita control]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Cita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Cita]
GO

/* Create Tables */

CREATE TABLE [Cita control]
(
	[Id_cita] int NOT NULL,
	[Fecha] date NOT NULL,
	[Estado] varchar(50) NOT NULL,
	[Id_hisorialCita] int NULL
)
GO

CREATE TABLE [Historial Cita]
(
	[Id_hisorialCita] int NOT NULL,
	[Resultado] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cita control] 
 ADD CONSTRAINT [PK_Id_cita]
	PRIMARY KEY CLUSTERED ([Id_cita] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cita control_Historial Cita] 
 ON [Cita control] ([Id_hisorialCita] ASC)
GO

ALTER TABLE [Historial Cita] 
 ADD CONSTRAINT [PK_Id_hisorialCita]
	PRIMARY KEY CLUSTERED ([Id_hisorialCita] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cita control] ADD CONSTRAINT [FK_Cita control_Historial Cita]
	FOREIGN KEY ([Id_hisorialCita]) REFERENCES quotedid ON DELETE No Action ON UPDATE No Action
GO
