/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Sep-2024 2:04:37 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cita control_Historial Cita]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cita control] DROP CONSTRAINT [FK_Cita control_Historial Cita]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluacion Electronica_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Evaluacion Electronica] DROP CONSTRAINT [FK_Evaluacion Electronica_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Cita_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Historial Cita] DROP CONSTRAINT [FK_Historial Cita_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Medico_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Historial Medico] DROP CONSTRAINT [FK_Historial Medico_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Horario Empleado_Empleado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Horario Empleado] DROP CONSTRAINT [FK_Horario Empleado_Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Informacion Cliente_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Informacion Cliente] DROP CONSTRAINT [FK_Informacion Cliente_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Usuario_Evaluacion Electronica]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Usuario] DROP CONSTRAINT [FK_Usuario_Evaluacion Electronica]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cita control]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cita control]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Evaluacion Electronica]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Evaluacion Electronica]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Formulario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Cita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Cita]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Medico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Medico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Horario Empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Horario Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Informacion Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Informacion Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Cita control]
(
	[ID_Cita] int NOT NULL,
	[Fecha] date NOT NULL,
	[Estado] varchar(50) NULL DEFAULT 'Pendiente',
	[ID_Historial] int NULL
)
GO

CREATE TABLE [Cliente]
(
	[ID_Cliente] int NOT NULL,
	[Telefono] varchar(50) NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Apellidos] varchar(50) NOT NULL,
	[Direccion] varchar(50) NULL DEFAULT 'No se indico la direccion',
	[Ciudad de residencia] varchar(50) NULL DEFAULT 'No se indico la ciudad de referencia',
	[Sexo] varchar(50) NOT NULL,
	[Edad] int NOT NULL,
	[Estatura] int NOT NULL,
	[ID_Formulario] int NULL
)
GO

CREATE TABLE [Empleado]
(
	[ID_Empleado] int NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Apellido] varchar(50) NOT NULL,
	[Direccion] varchar(50) NOT NULL,
	[ID_Usuario] int NULL
)
GO

CREATE TABLE [Evaluacion Electronica]
(
	[ID_Evaluacion Electronica] int NOT NULL,
	[Fecha] date NULL,
	[Peso] int NULL,
	[IMC] int NOT NULL,
	[Porcentaje Grasa] int NOT NULL,
	[Porcentaje Masa Muscular] int NOT NULL,
	[Metabolismo Basal] int NOT NULL,
	[Nivel Grasa Visceral] int NOT NULL,
	[Edad Biologica] int NOT NULL,
	[ID_Formulario] int NULL
)
GO

CREATE TABLE [Formulario]
(
	[ID_Formulario] int NOT NULL,
	[Fecha Inicio] date NOT NULL
)
GO

CREATE TABLE [Historial Cita]
(
	[ID_Historial] int NOT NULL,
	[Resultado] varchar(50) NULL,
	[ID_Formulario] int NULL
)
GO

CREATE TABLE [Historial Medico]
(
	[ID_Historial Medico] int NOT NULL,
	[Enfermedades Sufridas] varchar(50) NOT NULL,
	[Alergias] varchar(50) NOT NULL,
	[Problemas con el corazon] varchar(50) NOT NULL,
	[Padece de azucar] varchar(50) NOT NULL,
	[ID_Cliente] int NULL
)
GO

CREATE TABLE [Horario Empleado]
(
	[ID_Horario Empleado] int NOT NULL,
	[Hora Inicio] time(7) NOT NULL,
	[Hora Fin] time(7) NOT NULL,
	[ID_Empleado] int NULL
)
GO

CREATE TABLE [Informacion Cliente]
(
	[ID_Informacion Cliente] int NOT NULL,
	[Nivel de energia] varchar(50) NULL,
	[Actividad Fisica] varchar(50) NULL,
	[Nutricion Inicial] varchar(50) NULL,
	[Cantidad de Comidas al dia] int NULL,
	[Objetivo con su Cuerpo] varchar(50) NULL,
	[Descanso por la Noche] varchar(50) NULL,
	[ID_Cliente] int NULL
)
GO

CREATE TABLE [Usuario]
(
	[ID_Usuario] int NOT NULL,
	[Password] varchar(50) NOT NULL,
	[ID_Evaluacion Electronica] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cita control] 
 ADD CONSTRAINT [PK_Cita control]
	PRIMARY KEY CLUSTERED ([ID_Cita] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cita control_Historial Cita] 
 ON [Cita control] ([ID_Historial] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([ID_Cliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cliente_Formulario] 
 ON [Cliente] ([ID_Formulario] ASC)
GO

ALTER TABLE [Empleado] 
 ADD CONSTRAINT [PK_Empleado]
	PRIMARY KEY CLUSTERED ([ID_Empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado_Usuario] 
 ON [Empleado] ([ID_Usuario] ASC)
GO

ALTER TABLE [Evaluacion Electronica] 
 ADD CONSTRAINT [PK_Evaluacion Electronica]
	PRIMARY KEY CLUSTERED ([ID_Evaluacion Electronica] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Evaluacion Electronica_Formulario] 
 ON [Evaluacion Electronica] ([ID_Formulario] ASC)
GO

ALTER TABLE [Formulario] 
 ADD CONSTRAINT [PK_Formulario]
	PRIMARY KEY CLUSTERED ([ID_Formulario] ASC)
GO

ALTER TABLE [Historial Cita] 
 ADD CONSTRAINT [PK_Historial Cita]
	PRIMARY KEY CLUSTERED ([ID_Historial] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Historial Cita_Formulario] 
 ON [Historial Cita] ([ID_Formulario] ASC)
GO

ALTER TABLE [Historial Medico] 
 ADD CONSTRAINT [PK_Historial Medico]
	PRIMARY KEY CLUSTERED ([ID_Historial Medico] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Historial Medico_Cliente] 
 ON [Historial Medico] ([ID_Cliente] ASC)
GO

ALTER TABLE [Horario Empleado] 
 ADD CONSTRAINT [PK_Horario Empleado]
	PRIMARY KEY CLUSTERED ([ID_Horario Empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Horario Empleado_Empleado] 
 ON [Horario Empleado] ([ID_Empleado] ASC)
GO

ALTER TABLE [Informacion Cliente] 
 ADD CONSTRAINT [PK_Informacion Cliente]
	PRIMARY KEY CLUSTERED ([ID_Informacion Cliente] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Informacion Cliente_Cliente] 
 ON [Informacion Cliente] ([ID_Cliente] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([ID_Usuario] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Usuario_Evaluacion Electronica] 
 ON [Usuario] ([ID_Evaluacion Electronica] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cita control] ADD CONSTRAINT [FK_Cita control_Historial Cita]
	FOREIGN KEY ([ID_Historial]) REFERENCES [Historial Cita] ([ID_Historial]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Formulario]
	FOREIGN KEY ([ID_Formulario]) REFERENCES [Formulario] ([ID_Formulario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Usuario]
	FOREIGN KEY ([ID_Usuario]) REFERENCES [Usuario] ([ID_Usuario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Evaluacion Electronica] ADD CONSTRAINT [FK_Evaluacion Electronica_Formulario]
	FOREIGN KEY ([ID_Formulario]) REFERENCES [Formulario] ([ID_Formulario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Historial Cita] ADD CONSTRAINT [FK_Historial Cita_Formulario]
	FOREIGN KEY ([ID_Formulario]) REFERENCES [Formulario] ([ID_Formulario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Historial Medico] ADD CONSTRAINT [FK_Historial Medico_Cliente]
	FOREIGN KEY ([ID_Cliente]) REFERENCES [Cliente] ([ID_Cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Horario Empleado] ADD CONSTRAINT [FK_Horario Empleado_Empleado]
	FOREIGN KEY ([ID_Empleado]) REFERENCES [Empleado] ([ID_Empleado]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Informacion Cliente] ADD CONSTRAINT [FK_Informacion Cliente_Cliente]
	FOREIGN KEY ([ID_Cliente]) REFERENCES [Cliente] ([ID_Cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Usuario] ADD CONSTRAINT [FK_Usuario_Evaluacion Electronica]
	FOREIGN KEY ([ID_Evaluacion Electronica]) REFERENCES [Evaluacion Electronica] ([ID_Evaluacion Electronica]) ON DELETE No Action ON UPDATE No Action
GO

