/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Sep-2024 1:34:03 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cita control_Historial Cita]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cita control] DROP CONSTRAINT [FK_Cita control_Historial Cita]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cita control]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cita control]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Cita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Cita]
GO

/* Create Tables */

CREATE TABLE [Cita control]
(
	[ID_Cita] int NOT NULL,
	[Fecha] date NOT NULL,
	[Estado] varchar(50) NULL DEFAULT 'Pendiente',
	[ID_Historial] int NULL
)
GO

CREATE TABLE [Historial Cita]
(
	[ID_Historial] int NOT NULL,
	[Resultado] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cita control] 
 ADD CONSTRAINT [PK_Cita control]
	PRIMARY KEY CLUSTERED ([ID_Cita] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cita control_Historial Cita] 
 ON [Cita control] ([ID_Historial] ASC)
GO

ALTER TABLE [Historial Cita] 
 ADD CONSTRAINT [PK_Historial Cita]
	PRIMARY KEY CLUSTERED ([ID_Historial] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cita control] ADD CONSTRAINT [FK_Cita control_Historial Cita]
	FOREIGN KEY ([ID_Historial]) REFERENCES [Historial Cita] ([ID_Historial]) ON DELETE No Action ON UPDATE No Action
GO
