use Joselito

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:26 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cita Control]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cita Control]
GO

/* Create Tables */

CREATE TABLE [Cita Control]
(
	[Id_cita] int NOT NULL,    -- El identificador de cada cita
	[Id_cliente] int NULL,    -- Es el id que conecta con el cliente
	[Fecha cita] date NULL,    -- Es la fecha en la que se realizara o se realizo la cita
	[Estado] text NULL    -- Es el estado de cada cita: Pendiente, pospuesto, Realizado
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cita Control] 
 ADD CONSTRAINT [PK_Cita Control]
	PRIMARY KEY CLUSTERED ([Id_cita] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'El identificador de cada cita', 'Schema', [dbo], 'table', [Cita Control], 'column', [Id_cita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el id que conecta con el cliente', 'Schema', [dbo], 'table', [Cita Control], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la fecha en la que se realizara o se realizo la cita', 'Schema', [dbo], 'table', [Cita Control], 'column', [Fecha cita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el estado de cada cita: Pendiente, pospuesto, Realizado', 'Schema', [dbo], 'table', [Cita Control], 'column', [Estado]
GO