/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:26 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene_Informacion Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Tiene_Informacion Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tiene un _Historial medico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_tiene un _Historial medico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Cita_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Historial Cita_Cliente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

/* Create Tables */

CREATE TABLE [Cliente]
(
	[idCliente] int NOT NULL,    -- Es el identificador del cliente
	[Id_cliente] int NOT NULL,    -- Es el id con el que se identifica el cliente.
	[Telefono] int NOT NULL,    -- El telefono celular del cliente
	[Nombres] text NOT NULL,    -- Es el nombre del cliente
	[Apellidos] text NOT NULL,    -- El apellido del cliente.
	[Direccion] text NOT NULL,    -- La direccion de la residencia del cliente.
	[Ciudad de residencia] text NOT NULL,    -- Donde vive el cliente. Importante para la recomendacion del estilo de vida.
	[Sexo] text NOT NULL,    -- Es el sexo del cliente. Hombre o mujer
	[Edad] int NOT NULL,    -- La edad del cliente.
	[Estatura] int NOT NULL,    -- La estatura del cliente para su estudio.
	[id_informacionCliente] int NULL,    -- Es la FK que conecta con informacion general del cliente
	[Id_historialMedico] int NULL,    -- Es la FK que conecta con el historial medico del cliente
	[Id_historialCita] int NULL    -- Es la FK que conecta con el historial de citas del cliente
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([idCliente] ASC,[Id_cliente] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Tiene_Informacion Cliente]
	FOREIGN KEY ([id_informacionCliente]) REFERENCES [Informacion Cliente] ([id_informacionCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_tiene un _Historial medico]
	FOREIGN KEY ([Id_historialMedico]) REFERENCES [Historial medico] ([Id_historialMedico]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Historial Cita_Cliente]
	FOREIGN KEY ([Id_historialCita]) REFERENCES [Historial Cita] ([Id_historialCita]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [idCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el id con el que se identifica el cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El telefono celular del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Telefono]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el nombre del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Nombres]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El apellido del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Apellidos]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La direccion de la residencia del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Direccion]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Donde vive el cliente. Importante para la recomendacion del estilo de vida.', 'Schema', [dbo], 'table', [Cliente], 'column', [Ciudad de residencia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el sexo del cliente. Hombre o mujer', 'Schema', [dbo], 'table', [Cliente], 'column', [Sexo]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La edad del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Edad]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La estatura del cliente para su estudio.', 'Schema', [dbo], 'table', [Cliente], 'column', [Estatura]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con informacion general del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [id_informacionCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con el historial medico del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_historialMedico]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con el historial de citas del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_historialCita]
GO