/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:26 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado _Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado ] DROP CONSTRAINT [FK_Empleado _Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Horario empleado_Empleado ]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado ] DROP CONSTRAINT [FK_Horario empleado_Empleado ]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado ]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado ]
GO

/* Create Tables */

CREATE TABLE [Empleado ]
(
	[Id_empleado] int NOT NULL,    -- El identificador del empleado
	[Nombre] text NULL,    -- Nombre del empleado
	[Apellido] text NULL,    -- Apellido del empleado
	[Id_usuario] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Empleado ] 
 ADD CONSTRAINT [PK_Empleado ]
	PRIMARY KEY CLUSTERED ([Id_empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado _Usuario] 
 ON [Empleado ] ([Id_usuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Empleado ] ADD CONSTRAINT [FK_Empleado _Usuario]
	FOREIGN KEY ([Id_usuario]) REFERENCES [Usuario] ([Id_usuario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado ] ADD CONSTRAINT [FK_Horario empleado_Empleado ]
	FOREIGN KEY ([Id_empleado]) REFERENCES [Horario empleado] ([Id_empleado]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'El identificador del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Nombre del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Nombre]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Apellido del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Apellido]
GO