/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:26 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluacion electronica_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Evaluacion electronica] DROP CONSTRAINT [FK_Evaluacion electronica_Usuario]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Evaluacion electronica]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Evaluacion electronica]
GO

/* Create Tables */

CREATE TABLE [Evaluacion electronica]
(
	[Id_evaluacionElectronica] int NOT NULL,    -- identificador de cada evaluacion
	[Fecha] date NULL,    -- Fecha en la que se realizo la evaluacion
	[Peso] int NULL,    -- Peso actual del cliente
	[IMC] int NULL,    -- Indice de masa corporal del cliente
	[Porcentaje Grasa] int NULL,    -- Porcentaje de grasa del cliente
	[Porcentaje masa muscular] int NULL,    -- Campo requerido para el porcentaje de grasa
	[Metabolismo basal] int NULL,    -- Campo requerido para rellenar el metabolismo del cliente
	[Nivel Grasa visceral] int NULL,    -- El nivel de grasa visceral del cliente
	[Edad Biologica] int NULL,    -- la edad biologica del cliente
	[Id_empleado] int NULL,    -- Identificador FK del empleado que realizó la evaluaion
	[Id_usuario] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Evaluacion electronica] 
 ADD CONSTRAINT [PK_Evaluacion electronica]
	PRIMARY KEY CLUSTERED ([Id_evaluacionElectronica] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Evaluacion electronica_Usuario] 
 ON [Evaluacion electronica] ([Id_usuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Evaluacion electronica] ADD CONSTRAINT [FK_Evaluacion electronica_Usuario]
	FOREIGN KEY ([Id_usuario]) REFERENCES [Usuario] ([Id_usuario]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'identificador de cada evaluacion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Id_evaluacionElectronica]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Fecha en la que se realizo la evaluacion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Fecha]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Peso actual del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Peso]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Indice de masa corporal del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [IMC]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Porcentaje de grasa del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Porcentaje Grasa]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Campo requerido para el porcentaje de grasa', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Porcentaje masa muscular]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Campo requerido para rellenar el metabolismo del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Metabolismo basal]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El nivel de grasa visceral del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Nivel Grasa visceral]
GO

EXEC sp_addextendedproperty 'MS_Description', 'la edad biologica del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Edad Biologica]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador FK del empleado que realizó la evaluaion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Id_empleado]
GO