/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene un _Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Tiene un _Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Cita_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Historial Cita_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Posee muchas _Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Posee muchas _Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluacion electronica_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Evaluacion electronica_Formulario]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Formulario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Formulario]
GO

/* Create Tables */

CREATE TABLE [Formulario]
(
	[Id_formulario] int NOT NULL,    -- Identificador del formulario 
	[Fecha inicial] date NULL,    -- Es la fecha en la que se crea el formulario
	[idCliente] int NULL,    -- es el identificador del cliente
	[Id_cliente] int NULL,    -- identificador del cliente
	[Id_historialCita] int NULL,    -- identificador del historial
	[Id_evaluacionElectronica] int NULL    -- Identificador de evaluacion
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Formulario] 
 ADD CONSTRAINT [PK_Formulario]
	PRIMARY KEY CLUSTERED ([Id_formulario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Tiene un _Cliente]
	FOREIGN KEY ([Id_cliente],[idCliente]) REFERENCES [Cliente] ([idCliente],[Id_cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Historial Cita_Formulario]
	FOREIGN KEY ([Id_historialCita]) REFERENCES [Historial Cita] ([Id_historialCita]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Posee muchas _Formulario]
	FOREIGN KEY ([Id_formulario]) REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Evaluacion electronica_Formulario]
	FOREIGN KEY ([Id_evaluacionElectronica]) REFERENCES [Evaluacion electronica] ([Id_evaluacionElectronica]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Identificador del formulario ', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_formulario]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la fecha en la que se crea el formulario', 'Schema', [dbo], 'table', [Formulario], 'column', [Fecha inicial]
GO

EXEC sp_addextendedproperty 'MS_Description', 'es el identificador del cliente', 'Schema', [dbo], 'table', [Formulario], 'column', [idCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'identificador del cliente', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'identificador del historial', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_historialCita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de evaluacion', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_evaluacionElectronica]
GO