/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial medico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial medico]
GO

/* Create Tables */

CREATE TABLE [Historial medico]
(
	[Id_historialMedico] int NOT NULL,    -- Identificador de la tabla
	[Enfermedades pasadas] text NULL,    -- Enfermedades que haya padecido el cliente, es un campo importante para conocer cual es el estado de salud de este.
	[Sufre de alergias] text NULL,    -- Distintas alergias que pueda tener el cliente. 
	[Problemas con el corazon] text NULL,    -- El cliente especificara si tiene algun problema relacionado con el corazon. Ademas de que es lo que le afecta
	[Padece del azucar] text NULL    -- Este es un campo que contendra parte de la informacion del cliente para su posterior analisis
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Historial medico] 
 ADD CONSTRAINT [PK_Historial medico]
	PRIMARY KEY CLUSTERED ([Id_historialMedico] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la tabla', 'Schema', [dbo], 'table', [Historial medico], 'column', [Id_historialMedico]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Enfermedades que haya padecido el cliente, es un campo importante para conocer cual es el estado de salud de este.', 'Schema', [dbo], 'table', [Historial medico], 'column', [Enfermedades pasadas]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Distintas alergias que pueda tener el cliente. ', 'Schema', [dbo], 'table', [Historial medico], 'column', [Sufre de alergias]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El cliente especificara si tiene algun problema relacionado con el corazon. Ademas de que es lo que le afecta', 'Schema', [dbo], 'table', [Historial medico], 'column', [Problemas con el corazon]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Este es un campo que contendra parte de la informacion del cliente para su posterior analisis', 'Schema', [dbo], 'table', [Historial medico], 'column', [Padece del azucar]
GO