/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene_Cita Control]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Historial Cita] DROP CONSTRAINT [FK_Tiene_Cita Control]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Cita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Cita]
GO

/* Create Tables */

CREATE TABLE [Historial Cita]
(
	[Id_historialCita] int NOT NULL,    -- Es el identificador del historial de citas
	[Id_cliente] int NULL,    -- El identifiacdor de cada cliente
	[Resultado] text NULL,    -- Un resumen de la cita
	[Id_cliente] int NULL,    -- Identificador de cliente
	[Id_empleado] text NULL,    -- Identificador de empleado que lo atendio
	[Id_cita] int NULL    -- Identificador de la cita
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Historial Cita] 
 ADD CONSTRAINT [PK_Historial Cita]
	PRIMARY KEY CLUSTERED ([Id_historialCita] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Historial Cita] ADD CONSTRAINT [FK_Tiene_Cita Control]
	FOREIGN KEY ([Id_cita]) REFERENCES [Cita Control] ([Id_cita]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del historial de citas', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_historialCita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El identifiacdor de cada cliente', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Un resumen de la cita', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Resultado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de cliente', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de empleado que lo atendio', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la cita', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cita]
GO