/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Horario empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Horario empleado]
GO

/* Create Tables */

CREATE TABLE [Horario empleado]
(
	[Id_empleado] int NOT NULL,    -- Identificador del empleado
	[HoraInicio] time(7) NULL,    -- Hora de entrada del empleado
	[HoraFin] time(7) NULL    -- hora de salida del empleado
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Horario empleado] 
 ADD CONSTRAINT [PK_Horario empleado]
	PRIMARY KEY CLUSTERED ([Id_empleado] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Identificador del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Hora de entrada del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [HoraInicio]
GO

EXEC sp_addextendedproperty 'MS_Description', 'hora de salida del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [HoraFin]
GO