/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Informacion Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Informacion Cliente]
GO

/* Create Tables */

CREATE TABLE [Informacion Cliente]
(
	[id_informacionCliente] int NOT NULL,    -- Identificador de la tabla informacion cliente
	[Nivel de energia] text NULL,    -- El cliente debera de especificar como se siente durante el dia en base al rendimiento por actividad
	[Actividades fisicas realizadas] text NULL,    -- Es un campo para guardar las actividades fisicas que practica el cliente
	[Nutricion inicial] text NULL,    -- Como es la nutricion actual del cliente.
	[Cantidad de comidas al dia] text NULL,    -- Cuantas veces al dia como el cliente
	[Objetivo con su cuerpo] text NULL,    -- El objetivo que tiene el cliente con su cuerpo
	[Descanso por la noche] text NULL    -- La calidad de sueño que tiene el cliente por las noches
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Informacion Cliente] 
 ADD CONSTRAINT [PK_Informacion Cliente]
	PRIMARY KEY CLUSTERED ([id_informacionCliente] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la tabla informacion cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [id_informacionCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El cliente debera de especificar como se siente durante el dia en base al rendimiento por actividad', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Nivel de energia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es un campo para guardar las actividades fisicas que practica el cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Actividades fisicas realizadas]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Como es la nutricion actual del cliente.', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Nutricion inicial]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Cuantas veces al dia como el cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Cantidad de comidas al dia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El objetivo que tiene el cliente con su cuerpo', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Objetivo con su cuerpo]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La calidad de sueño que tiene el cliente por las noches', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Descanso por la noche]
GO