/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:22:27 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Usuario]
(
	[Id_usuario] int NOT NULL,    -- Es el identificador del usuario
	[id_cliente] int NOT NULL,    -- Es el identificador con el que se asociara al cliente
	[contraseña] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([Id_usuario] ASC)
GO

/* Create Table Comments */


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Usuario', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Esta tabla contiene la informacion del usuario que rellenara la informacion de los formularios. Estara relacionada con la evaluacion y con un empleado', 'SCHEMA', 'dbo', 'table', 'Usuario' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Esta tabla contiene la informacion del usuario que rellenara la informacion de los formularios. Estara relacionada con la evaluacion y con un empleado', 'SCHEMA', 'dbo', 'table', 'Usuario' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del usuario', 'Schema', [dbo], 'table', [Usuario], 'column', [Id_usuario]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador con el que se asociara al cliente', 'Schema', [dbo], 'table', [Usuario], 'column', [id_cliente]
GO