

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 3:53:15 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tbl_empleado_Tbl_departamento_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [tbl_empleado] DROP CONSTRAINT [FK_tbl_empleado_Tbl_departamento_02]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tbl_departamento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tbl_departamento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tbl_empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tbl_empleado]
GO

/* Create Tables */

CREATE TABLE [Tbl_departamento]
(
	[Nom_departamento] varchar(150) NOT NULL,
	[Estado_departamento] bit NOT NULL,
	[id_departamento] int NOT NULL
)
GO

CREATE TABLE [tbl_empleado]
(
	[Id_empleado] int NOT NULL,
	[Nombre_empleado] varchar(150) NOT NULL,
	[Estado_empleado] bit NOT NULL,
	[Id_departamento] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Tbl_departamento] 
 ADD CONSTRAINT [PK_Tbl_departamento]
	PRIMARY KEY CLUSTERED ([id_departamento] ASC)
GO

ALTER TABLE [tbl_empleado] 
 ADD CONSTRAINT [PK_Tbl_empleado]
	PRIMARY KEY CLUSTERED ([Id_empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_tbl_empleado_Tbl_departamento_02] 
 ON [tbl_empleado] ([Id_departamento] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [tbl_empleado] ADD CONSTRAINT [FK_tbl_empleado_Tbl_departamento_02]
	FOREIGN KEY ([Id_departamento]) REFERENCES [Tbl_departamento] ([id_departamento]) ON DELETE No Action ON UPDATE No Action
GO
