/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 10-Sep-2024 4:00:23 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene_Informacion Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Tiene_Informacion Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_tiene un _Historial medico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_tiene un _Historial medico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Cita_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Historial Cita_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado _Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado ] DROP CONSTRAINT [FK_Empleado _Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Horario empleado_Empleado ]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado ] DROP CONSTRAINT [FK_Horario empleado_Empleado ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluacion electronica_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Evaluacion electronica] DROP CONSTRAINT [FK_Evaluacion electronica_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene un _Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Tiene un _Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Historial Cita_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Historial Cita_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Posee muchas _Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Posee muchas _Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluacion electronica_Formulario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Formulario] DROP CONSTRAINT [FK_Evaluacion electronica_Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tiene_Cita Control]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Historial Cita] DROP CONSTRAINT [FK_Tiene_Cita Control]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cita Control]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cita Control]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado ]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Evaluacion electronica]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Evaluacion electronica]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Formulario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Formulario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial Cita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial Cita]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Historial medico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Historial medico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Horario empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Horario empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Informacion Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Informacion Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Cita Control]
(
	[Id_cita] int NOT NULL,    -- El identificador de cada cita
	[Id_cliente] int NULL,    -- Es el id que conecta con el cliente
	[Fecha cita] date NULL,    -- Es la fecha en la que se realizara o se realizo la cita
	[Estado] text NULL    -- Es el estado de cada cita: Pendiente, pospuesto, Realizado
)
GO

CREATE TABLE [Cliente]
(
	[idCliente] int NOT NULL,    -- Es el identificador del cliente
	[Id_cliente] int NOT NULL,    -- Es el id con el que se identifica el cliente.
	[Telefono] int NOT NULL,    -- El telefono celular del cliente
	[Nombres] text NOT NULL,    -- Es el nombre del cliente
	[Apellidos] text NOT NULL,    -- El apellido del cliente.
	[Direccion] text NOT NULL,    -- La direccion de la residencia del cliente.
	[Ciudad de residencia] text NOT NULL,    -- Donde vive el cliente. Importante para la recomendacion del estilo de vida.
	[Sexo] text NOT NULL,    -- Es el sexo del cliente. Hombre o mujer
	[Edad] int NOT NULL,    -- La edad del cliente.
	[Estatura] int NOT NULL,    -- La estatura del cliente para su estudio.
	[id_informacionCliente] int NULL,    -- Es la FK que conecta con informacion general del cliente
	[Id_historialMedico] int NULL,    -- Es la FK que conecta con el historial medico del cliente
	[Id_historialCita] int NULL    -- Es la FK que conecta con el historial de citas del cliente
)
GO

CREATE TABLE [Empleado ]
(
	[Id_empleado] int NOT NULL,    -- El identificador del empleado
	[Nombre] text NULL,    -- Nombre del empleado
	[Apellido] text NULL,    -- Apellido del empleado
	[Id_usuario] int NULL
)
GO

CREATE TABLE [Evaluacion electronica]
(
	[Id_evaluacionElectronica] int NOT NULL,    -- identificador de cada evaluacion
	[Fecha] date NULL,    -- Fecha en la que se realizo la evaluacion
	[Peso] int NULL,    -- Peso actual del cliente
	[IMC] int NULL,    -- Indice de masa corporal del cliente
	[Porcentaje Grasa] int NULL,    -- Porcentaje de grasa del cliente
	[Porcentaje masa muscular] int NULL,    -- Campo requerido para el porcentaje de grasa
	[Metabolismo basal] int NULL,    -- Campo requerido para rellenar el metabolismo del cliente
	[Nivel Grasa visceral] int NULL,    -- El nivel de grasa visceral del cliente
	[Edad Biologica] int NULL,    -- la edad biologica del cliente
	[Id_empleado] int NULL,    -- Identificador FK del empleado que realizó la evaluaion
	[Id_usuario] int NULL
)
GO

CREATE TABLE [Formulario]
(
	[Id_formulario] int NOT NULL,    -- Identificador del formulario 
	[Fecha inicial] date NULL,    -- Es la fecha en la que se crea el formulario
	[idCliente] int NULL,    -- es el identificador del cliente
	[Id_cliente] int NULL,    -- identificador del cliente
	[Id_historialCita] int NULL,    -- identificador del historial
	[Id_evaluacionElectronica] int NULL    -- Identificador de evaluacion
)
GO

CREATE TABLE [Historial Cita]
(
	[Id_historialCita] int NOT NULL,    -- Es el identificador del historial de citas
	[Id_cliente] int NULL,    -- El identifiacdor de cada cliente
	[Resultado] text NULL,    -- Un resumen de la cita
	[Id_cliente] int NULL,    -- Identificador de cliente
	[Id_empleado] text NULL,    -- Identificador de empleado que lo atendio
	[Id_cita] int NULL    -- Identificador de la cita
)
GO

CREATE TABLE [Historial medico]
(
	[Id_historialMedico] int NOT NULL,    -- Identificador de la tabla
	[Enfermedades pasadas] text NULL,    -- Enfermedades que haya padecido el cliente, es un campo importante para conocer cual es el estado de salud de este.
	[Sufre de alergias] text NULL,    -- Distintas alergias que pueda tener el cliente. 
	[Problemas con el corazon] text NULL,    -- El cliente especificara si tiene algun problema relacionado con el corazon. Ademas de que es lo que le afecta
	[Padece del azucar] text NULL    -- Este es un campo que contendra parte de la informacion del cliente para su posterior analisis
)
GO

CREATE TABLE [Horario empleado]
(
	[Id_empleado] int NOT NULL,    -- Identificador del empleado
	[HoraInicio] time(7) NULL,    -- Hora de entrada del empleado
	[HoraFin] time(7) NULL    -- hora de salida del empleado
)
GO

CREATE TABLE [Informacion Cliente]
(
	[id_informacionCliente] int NOT NULL,    -- Identificador de la tabla informacion cliente
	[Nivel de energia] text NULL,    -- El cliente debera de especificar como se siente durante el dia en base al rendimiento por actividad
	[Actividades fisicas realizadas] text NULL,    -- Es un campo para guardar las actividades fisicas que practica el cliente
	[Nutricion inicial] text NULL,    -- Como es la nutricion actual del cliente.
	[Cantidad de comidas al dia] text NULL,    -- Cuantas veces al dia como el cliente
	[Objetivo con su cuerpo] text NULL,    -- El objetivo que tiene el cliente con su cuerpo
	[Descanso por la noche] text NULL    -- La calidad de sueño que tiene el cliente por las noches
)
GO

CREATE TABLE [Usuario]
(
	[Id_usuario] int NOT NULL,    -- Es el identificador del usuario
	[id_cliente] int NOT NULL,    -- Es el identificador con el que se asociara al cliente
	[contraseña] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cita Control] 
 ADD CONSTRAINT [PK_Cita Control]
	PRIMARY KEY CLUSTERED ([Id_cita] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([idCliente] ASC,[Id_cliente] ASC)
GO

ALTER TABLE [Empleado ] 
 ADD CONSTRAINT [PK_Empleado ]
	PRIMARY KEY CLUSTERED ([Id_empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado _Usuario] 
 ON [Empleado ] ([Id_usuario] ASC)
GO

ALTER TABLE [Evaluacion electronica] 
 ADD CONSTRAINT [PK_Evaluacion electronica]
	PRIMARY KEY CLUSTERED ([Id_evaluacionElectronica] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Evaluacion electronica_Usuario] 
 ON [Evaluacion electronica] ([Id_usuario] ASC)
GO

ALTER TABLE [Formulario] 
 ADD CONSTRAINT [PK_Formulario]
	PRIMARY KEY CLUSTERED ([Id_formulario] ASC)
GO

ALTER TABLE [Historial Cita] 
 ADD CONSTRAINT [PK_Historial Cita]
	PRIMARY KEY CLUSTERED ([Id_historialCita] ASC)
GO

ALTER TABLE [Historial medico] 
 ADD CONSTRAINT [PK_Historial medico]
	PRIMARY KEY CLUSTERED ([Id_historialMedico] ASC)
GO

ALTER TABLE [Horario empleado] 
 ADD CONSTRAINT [PK_Horario empleado]
	PRIMARY KEY CLUSTERED ([Id_empleado] ASC)
GO

ALTER TABLE [Informacion Cliente] 
 ADD CONSTRAINT [PK_Informacion Cliente]
	PRIMARY KEY CLUSTERED ([id_informacionCliente] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([Id_usuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Tiene_Informacion Cliente]
	FOREIGN KEY ([id_informacionCliente]) REFERENCES [Informacion Cliente] ([id_informacionCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_tiene un _Historial medico]
	FOREIGN KEY ([Id_historialMedico]) REFERENCES [Historial medico] ([Id_historialMedico]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Historial Cita_Cliente]
	FOREIGN KEY ([Id_historialCita]) REFERENCES [Historial Cita] ([Id_historialCita]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado ] ADD CONSTRAINT [FK_Empleado _Usuario]
	FOREIGN KEY ([Id_usuario]) REFERENCES [Usuario] ([Id_usuario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado ] ADD CONSTRAINT [FK_Horario empleado_Empleado ]
	FOREIGN KEY ([Id_empleado]) REFERENCES [Horario empleado] ([Id_empleado]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Evaluacion electronica] ADD CONSTRAINT [FK_Evaluacion electronica_Usuario]
	FOREIGN KEY ([Id_usuario]) REFERENCES [Usuario] ([Id_usuario]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Tiene un _Cliente]
	FOREIGN KEY ([Id_cliente],[idCliente]) REFERENCES [Cliente] ([idCliente],[Id_cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Historial Cita_Formulario]
	FOREIGN KEY ([Id_historialCita]) REFERENCES [Historial Cita] ([Id_historialCita]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Posee muchas _Formulario]
	FOREIGN KEY ([Id_formulario]) REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Formulario] ADD CONSTRAINT [FK_Evaluacion electronica_Formulario]
	FOREIGN KEY ([Id_evaluacionElectronica]) REFERENCES [Evaluacion electronica] ([Id_evaluacionElectronica]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Historial Cita] ADD CONSTRAINT [FK_Tiene_Cita Control]
	FOREIGN KEY ([Id_cita]) REFERENCES [Cita Control] ([Id_cita]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'El identificador de cada cita', 'Schema', [dbo], 'table', [Cita Control], 'column', [Id_cita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el id que conecta con el cliente', 'Schema', [dbo], 'table', [Cita Control], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la fecha en la que se realizara o se realizo la cita', 'Schema', [dbo], 'table', [Cita Control], 'column', [Fecha cita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el estado de cada cita: Pendiente, pospuesto, Realizado', 'Schema', [dbo], 'table', [Cita Control], 'column', [Estado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [idCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el id con el que se identifica el cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El telefono celular del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Telefono]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el nombre del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Nombres]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El apellido del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Apellidos]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La direccion de la residencia del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Direccion]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Donde vive el cliente. Importante para la recomendacion del estilo de vida.', 'Schema', [dbo], 'table', [Cliente], 'column', [Ciudad de residencia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el sexo del cliente. Hombre o mujer', 'Schema', [dbo], 'table', [Cliente], 'column', [Sexo]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La edad del cliente.', 'Schema', [dbo], 'table', [Cliente], 'column', [Edad]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La estatura del cliente para su estudio.', 'Schema', [dbo], 'table', [Cliente], 'column', [Estatura]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con informacion general del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [id_informacionCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con el historial medico del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_historialMedico]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la FK que conecta con el historial de citas del cliente', 'Schema', [dbo], 'table', [Cliente], 'column', [Id_historialCita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El identificador del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Nombre del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Nombre]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Apellido del empleado', 'Schema', [dbo], 'table', [Empleado ], 'column', [Apellido]
GO

EXEC sp_addextendedproperty 'MS_Description', 'identificador de cada evaluacion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Id_evaluacionElectronica]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Fecha en la que se realizo la evaluacion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Fecha]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Peso actual del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Peso]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Indice de masa corporal del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [IMC]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Porcentaje de grasa del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Porcentaje Grasa]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Campo requerido para el porcentaje de grasa', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Porcentaje masa muscular]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Campo requerido para rellenar el metabolismo del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Metabolismo basal]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El nivel de grasa visceral del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Nivel Grasa visceral]
GO

EXEC sp_addextendedproperty 'MS_Description', 'la edad biologica del cliente', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Edad Biologica]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador FK del empleado que realizó la evaluaion', 'Schema', [dbo], 'table', [Evaluacion electronica], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador del formulario ', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_formulario]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es la fecha en la que se crea el formulario', 'Schema', [dbo], 'table', [Formulario], 'column', [Fecha inicial]
GO

EXEC sp_addextendedproperty 'MS_Description', 'es el identificador del cliente', 'Schema', [dbo], 'table', [Formulario], 'column', [idCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'identificador del cliente', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'identificador del historial', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_historialCita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de evaluacion', 'Schema', [dbo], 'table', [Formulario], 'column', [Id_evaluacionElectronica]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del historial de citas', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_historialCita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El identifiacdor de cada cliente', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Un resumen de la cita', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Resultado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de cliente', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de empleado que lo atendio', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la cita', 'Schema', [dbo], 'table', [Historial Cita], 'column', [Id_cita]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la tabla', 'Schema', [dbo], 'table', [Historial medico], 'column', [Id_historialMedico]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Enfermedades que haya padecido el cliente, es un campo importante para conocer cual es el estado de salud de este.', 'Schema', [dbo], 'table', [Historial medico], 'column', [Enfermedades pasadas]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Distintas alergias que pueda tener el cliente. ', 'Schema', [dbo], 'table', [Historial medico], 'column', [Sufre de alergias]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El cliente especificara si tiene algun problema relacionado con el corazon. Ademas de que es lo que le afecta', 'Schema', [dbo], 'table', [Historial medico], 'column', [Problemas con el corazon]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Este es un campo que contendra parte de la informacion del cliente para su posterior analisis', 'Schema', [dbo], 'table', [Historial medico], 'column', [Padece del azucar]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [Id_empleado]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Hora de entrada del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [HoraInicio]
GO

EXEC sp_addextendedproperty 'MS_Description', 'hora de salida del empleado', 'Schema', [dbo], 'table', [Horario empleado], 'column', [HoraFin]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Identificador de la tabla informacion cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [id_informacionCliente]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El cliente debera de especificar como se siente durante el dia en base al rendimiento por actividad', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Nivel de energia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es un campo para guardar las actividades fisicas que practica el cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Actividades fisicas realizadas]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Como es la nutricion actual del cliente.', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Nutricion inicial]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Cuantas veces al dia como el cliente', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Cantidad de comidas al dia]
GO

EXEC sp_addextendedproperty 'MS_Description', 'El objetivo que tiene el cliente con su cuerpo', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Objetivo con su cuerpo]
GO

EXEC sp_addextendedproperty 'MS_Description', 'La calidad de sueño que tiene el cliente por las noches', 'Schema', [dbo], 'table', [Informacion Cliente], 'column', [Descanso por la noche]
GO


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Usuario', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Esta tabla contiene la informacion del usuario que rellenara la informacion de los formularios. Estara relacionada con la evaluacion y con un empleado', 'SCHEMA', 'dbo', 'table', 'Usuario' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Esta tabla contiene la informacion del usuario que rellenara la informacion de los formularios. Estara relacionada con la evaluacion y con un empleado', 'SCHEMA', 'dbo', 'table', 'Usuario' 
end

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador del usuario', 'Schema', [dbo], 'table', [Usuario], 'column', [Id_usuario]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Es el identificador con el que se asociara al cliente', 'Schema', [dbo], 'table', [Usuario], 'column', [id_cliente]
GO
